name: Automation - Changelog Update

on:
  workflow_dispatch:
  push:
    branches: [ 1.x ]

jobs:
  automation:
    uses: aeon-php/actions/.github/workflows/automation-changelog-update.yml@main
    secrets:
      automation_github_token: "${{ secrets.ACCESS_TOKEN }}"
